### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by mohanagr** [mohanagr/webchat#1]
# Features to add
- [ ] Add option for the host (server) to decide if he wants to be a part of the chat room (receive all of clients' messages or not).
- [ ] Add support for in-chat commands like - `Ping` (Pong), `Quit` and `@` for private messages.
- [ ] Allow host to `kick` a client.
